spring:
  application:
    name: service-gateway

server:
  port: 8082

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
#    org.springframework.boot.autoconfigure: DEBUG

jwt:
  public.key: classpath:app.pub