GET http://localhost:8082/jeu/
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoieW9oYW4iLCJleHAiOjE2NzU0NTUwNDMsImlhdCI6MTY3NTQxOTA0Mywic2NvcGUiOiIifQ.iF6nOd56A88F44ikq7ZhF0aCZOlyPV7lHBflCQ1yKFx9srYC4_Kd6NRYJYVxgk3JqsQjGsrmPxlyZLvlhSD4kjiuzZar8_9c3oOVmgogMzT3OyJ68Y3Y7-fSWg6fQYqYn1L7qSi3xn9AYT8CXbm9lV2ONhFsE5L5ZZBiDq7rq-cnd6akB2kVry3trIGCE1_3ry48Qlm1tAfLlLgX6YkkW-PEfppGq-Gzz84XUmrWLOGM6mqhXkhASSTkC-sKsNzMEX3MekQ0T-rh8buDWb-hYmqqjQt5mimoSR_r6rsrdTHu2ZCUgrb_DB5ACqzJToaU0dXo7kEiuDOJEDLEPmKAZg
